
:toc:               left
:toc-title:         Connector Summary
:toclevels:         2
:last-update-label!:
:docinfo:
:source-highlighter: coderay
:icons: font


= Wechat Connector API Reference


*Additional Info*
[width="50", cols=".<60%,^40%" ]
|======================
| Requires Mule Enterprise License |  No icon:remove[]  {nbsp}
| Requires Entitlement |  No icon:remove[]  {nbsp}
| Mule Version | 3.5.0 or higher
|======================


== Configs
---
=== Configuration
`<wechat:config-wechat>`



`Configuration` 


==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| token | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Token set by the developer on the WeChat Official Account Admin Platform+++ |   | *x*{nbsp}
| appId | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The unique certificate of a official account+++ |   | *x*{nbsp}
| appSecret | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The key of a official account's certificate+++ |   | *x*{nbsp}
| selfManageAccessToken | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Self-Manage Access Token+++ |  false | {nbsp}
|======================



== Processors

---

=== Verify url
`<wechat:verify-url>`




+++
Verify validity of the URL
</br>http://admin.wechat.com/wiki/index.php?title=Getting_Started#Step_2._Verify_validity_of_the_URL
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
uri  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++URI sent by WeChat Official Account Admin System+++ | #[message.inboundProperties.'http.request.uri'] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>+++ | +++The developer's backend system should return the echostr parameter value indicating that the request has been successfully received+++
|======================




---

=== Message decryption
`<wechat:message-decryption>`




+++
Authenticate message validity and obtain decrypted message.
</br><a href="http://admin.wechat.com/wiki/index.php?title=Implementation_Guide">http://admin.wechat.com/wiki/index.php?title=Implementation_Guide</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
encrytedXml icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Encryted message.+++ | #[payload] | {nbsp}




| 
encodingAesKey  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++EncodingAESKey set by the developer on the WeChat Official Account Admin Platform+++ |  | *x*{nbsp}




| 
uri  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++URI sent by WeChat Official Account Admin System+++ | #[message.inboundProperties.'http.request.uri'] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++String XML+++
|======================




---

=== Message encrytion
`<wechat:message-encrytion>`




+++
Encrypt a reply message from an official account
</br><a href="http://admin.wechat.com/wiki/index.php?title=Implementation_Guide">http://admin.wechat.com/wiki/index.php?title=Implementation_Guide</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
replyXml icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Reply message from an official account+++ | #[payload] | {nbsp}




| 
encodingAesKey  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++EncodingAESKey set by the developer on the WeChat Official Account Admin Platform+++ |  | *x*{nbsp}




| 
uri  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++URI sent by WeChat Official Account Admin System+++ | #[message.inboundProperties.'http.request.uri'] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++String XML+++
|======================




---

=== Upload temporary image file
`<wechat:upload-temporary-image-file>`




+++
Upload Temporary Image Material
</br><a href="http://admin.wechat.com/wiki/index.php?title=Transferring_Multimedia_Files">http://admin.wechat.com/wiki/index.php?title=Transferring_Multimedia_Files</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| payload icon:envelope[] | +++Document+++ | *The current message payload is automatically transformed and injected to this parameter.* +++<br>+++ | #[payload] | {nbsp}




| 
attachment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,DataHandler>+++ | +++Attached file+++ | #[message.inboundAttachments] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++HashMap+++
|======================




---

=== Upload temporary voice file
`<wechat:upload-temporary-voice-file>`




+++
Upload Temporary Voice Material
</br><a href="http://admin.wechat.com/wiki/index.php?title=Transferring_Multimedia_Files">http://admin.wechat.com/wiki/index.php?title=Transferring_Multimedia_Files</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| payload icon:envelope[] | +++Document+++ | *The current message payload is automatically transformed and injected to this parameter.* +++<br>+++ | #[payload] | {nbsp}




| 
attachment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,DataHandler>+++ | +++Attached file+++ | #[message.inboundAttachments] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++HashMap+++
|======================




---

=== Upload temporary video file
`<wechat:upload-temporary-video-file>`




+++
Upload Temporary Video Material
</br><a href="http://admin.wechat.com/wiki/index.php?title=Transferring_Multimedia_Files">http://admin.wechat.com/wiki/index.php?title=Transferring_Multimedia_Files</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| payload icon:envelope[] | +++Document+++ | *The current message payload is automatically transformed and injected to this parameter.* +++<br>+++ | #[payload] | {nbsp}




| 
attachment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,DataHandler>+++ | +++Attached file+++ | #[message.inboundAttachments] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++HashMap+++
|======================




---

=== Upload temporary thumb file
`<wechat:upload-temporary-thumb-file>`




+++
Upload Temporary Thumb Material
</br><a href="http://admin.wechat.com/wiki/index.php?title=Transferring_Multimedia_Files">http://admin.wechat.com/wiki/index.php?title=Transferring_Multimedia_Files</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| payload icon:envelope[] | +++Document+++ | *The current message payload is automatically transformed and injected to this parameter.* +++<br>+++ | #[payload] | {nbsp}




| 
attachment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,DataHandler>+++ | +++Attached file+++ | #[message.inboundAttachments] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++HashMap+++
|======================




---

=== Upload permanent image file
`<wechat:upload-permanent-image-file>`




+++
Upload Permanent Image Material
</br><a href="http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/oa/asset-management/upload-perm-asset#asset-management_upload-perm-asset">http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/oa/asset-management/upload-perm-asset#asset-management_upload-perm-asset</a>
+++


    
                
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
title  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The title of this image.+++ |  | *x*{nbsp}




| payload icon:envelope[] | +++Document+++ | *The current message payload is automatically transformed and injected to this parameter.* +++<br>+++ | #[payload] | {nbsp}




| 
attachment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,DataHandler>+++ | +++Attached file+++ | #[message.inboundAttachments] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++HashMap+++
|======================




---

=== Upload permanent voice file
`<wechat:upload-permanent-voice-file>`




+++
Upload Permanent Voice Material
</br><a href="http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/oa/asset-management/upload-perm-asset#asset-management_upload-perm-asset">http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/oa/asset-management/upload-perm-asset#asset-management_upload-perm-asset</a>
+++


    
                
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
title  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The title of this voice.+++ |  | *x*{nbsp}




| payload icon:envelope[] | +++Document+++ | *The current message payload is automatically transformed and injected to this parameter.* +++<br>+++ | #[payload] | {nbsp}




| 
attachment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,DataHandler>+++ | +++Attached file+++ | #[message.inboundAttachments] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++HashMap+++
|======================




---

=== Upload permanent video file
`<wechat:upload-permanent-video-file>`




+++
Upload Permanent Video Material
</br><a href="http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/oa/asset-management/upload-perm-asset#asset-management_upload-perm-asset">http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/oa/asset-management/upload-perm-asset#asset-management_upload-perm-asset</a>
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
title  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The title of this video.+++ |  | *x*{nbsp}




| 
introduction  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A description for this video.+++ |  | *x*{nbsp}




| payload icon:envelope[] | +++Document+++ | *The current message payload is automatically transformed and injected to this parameter.* +++<br>+++ | #[payload] | {nbsp}




| 
attachment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,DataHandler>+++ | +++Attached file+++ | #[message.inboundAttachments] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++HashMap+++
|======================




---

=== Upload permanent thumb file
`<wechat:upload-permanent-thumb-file>`




+++
Upload Permanent Thumb Material
</br><a href="http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/oa/asset-management/upload-perm-asset#asset-management_upload-perm-asset">http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/oa/asset-management/upload-perm-asset#asset-management_upload-perm-asset</a>
+++


    
                
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
title  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The title of this thumb.+++ |  | *x*{nbsp}




| payload icon:envelope[] | +++Document+++ | *The current message payload is automatically transformed and injected to this parameter.* +++<br>+++ | #[payload] | {nbsp}




| 
attachment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,DataHandler>+++ | +++Attached file+++ | #[message.inboundAttachments] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++HashMap+++
|======================




---

=== Customer text message
`<wechat:customer-text-message>`




+++
Send Customer Text Message to OpenId
</br><a href="http://admin.wechat.com/wiki/index.php?title=Customer_Service_Messages#Text_Message">http://admin.wechat.com/wiki/index.php?title=Customer_Service_Messages#Text_Message</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
openId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Follower's openId+++ |  | *x*{nbsp}




| 
content  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Text Message+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Customer image message
`<wechat:customer-image-message>`




+++
Send Customer Image Message to OpenId
</br><a href="http://admin.wechat.com/wiki/index.php?title=Customer_Service_Messages#Image_Message">http://admin.wechat.com/wiki/index.php?title=Customer_Service_Messages#Image_Message</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
openId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Follower's openId+++ |  | *x*{nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Image Materials' mediaId+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Customer audio message
`<wechat:customer-audio-message>`




+++
Send Customer Audio Message to OpenId
</br><a href="http://admin.wechat.com/wiki/index.php?title=Customer_Service_Messages#Audio_Message">http://admin.wechat.com/wiki/index.php?title=Customer_Service_Messages#Audio_Message</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
openId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Follower's openId+++ |  | *x*{nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Audio Materials' mediaId+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Customer video message
`<wechat:customer-video-message>`




+++
Send Customer Video Message to OpenId
</br><a href="http://admin.wechat.com/wiki/index.php?title=Customer_Service_Messages#Video_Message">http://admin.wechat.com/wiki/index.php?title=Customer_Service_Messages#Video_Message</a>
+++


    
                
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
openId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Follower's openId+++ |  | *x*{nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Video Materials' mediaId+++ |  | *x*{nbsp}




| 
thumbMediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Video Materials' thumbMediaId+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Customer music message
`<wechat:customer-music-message>`




+++
Send Customer Music Message to OpenId
</br><a href="http://admin.wechat.com/wiki/index.php?title=Customer_Service_Messages#Music_Message">http://admin.wechat.com/wiki/index.php?title=Customer_Service_Messages#Music_Message</a>
+++


    
                            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
openId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Follower's openId+++ |  | *x*{nbsp}




| 
title  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Music title+++ |  | *x*{nbsp}




| 
description  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Music description+++ |  | *x*{nbsp}




| 
musicUrl  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Music URL+++ |  | *x*{nbsp}




| 
hqMusicUrl  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++High-quality URL that WeChat accesses on WiFi+++ |  | *x*{nbsp}




| 
thumbMediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The media ID of the thumb+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Upload article message data
`<wechat:upload-article-message-data>`



icon:cloud[] {nbsp} DataSense enabled

+++
Upload Article Message Data
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Upload_Article_Message_Data">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Upload_Article_Message_Data</a>
+++


    
                
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
ApiName icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Upload Article Message Data+++ | UploadArticleMessageData | {nbsp}




| 
articles icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>>+++ | +++Articles of Upload Article Message Data API+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Group based broadcast article
`<wechat:group-based-broadcast-article>`




+++
Group-Based Broadcast Article
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Group-Based_Broadcast">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Group-Based_Broadcast</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
groupId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of any groups to be broadcast to+++ |  | *x*{nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of the message to be broadcast+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Group based broadcast text
`<wechat:group-based-broadcast-text>`




+++
Group-Based Broadcast Text
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Group-Based_Broadcast">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Group-Based_Broadcast</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
groupId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of any groups to be broadcast to+++ |  | *x*{nbsp}




| 
content  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Text content+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Group based broadcast voice
`<wechat:group-based-broadcast-voice>`




+++
Group-Based Broadcast Voice
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Group-Based_Broadcast">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Group-Based_Broadcast</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
groupId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of any groups to be broadcast to+++ |  | *x*{nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of the message to be broadcast+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Group based broadcast image
`<wechat:group-based-broadcast-image>`




+++
Group-Based Broadcast Image
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Group-Based_Broadcast">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Group-Based_Broadcast</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
groupId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of any groups to be broadcast to+++ |  | *x*{nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of the message to be broadcast+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Group based broadcast video
`<wechat:group-based-broadcast-video>`




+++
Group-Based Broadcast Video
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Group-Based_Broadcast">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Group-Based_Broadcast</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
groupId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of any groups to be broadcast to+++ |  | *x*{nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of the message to be broadcast+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Open id list broadcast article
`<wechat:open-id-list-broadcast-article>`



icon:cloud[] {nbsp} DataSense enabled

+++
OpenID List-Based Broadcast Article
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#OpenID_List-Based_Broadcast">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#OpenID_List-Based_Broadcast</a>
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of the message to be broadcast+++ |  | *x*{nbsp}




| 
ApiName icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++OpenID List Broadcast Article+++ | OpenIDListBroadcastArticle | {nbsp}




| 
toUser icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++List of Follower's openId+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Open id list broadcast text
`<wechat:open-id-list-broadcast-text>`



icon:cloud[] {nbsp} DataSense enabled

+++
OpenID List-Based Broadcast Text
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#OpenID_List-Based_Broadcast">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#OpenID_List-Based_Broadcast</a>
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
content  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Text content+++ |  | *x*{nbsp}




| 
ApiName icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++OpenID List Broadcast Text+++ | OpenIDListBroadcastText | {nbsp}




| 
toUser icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++List of Follower's openId+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Open id list broadcast voice
`<wechat:open-id-list-broadcast-voice>`



icon:cloud[] {nbsp} DataSense enabled

+++
OpenID List-Based Broadcast Voice
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#OpenID_List-Based_Broadcast">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#OpenID_List-Based_Broadcast</a>
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of the message to be broadcast+++ |  | *x*{nbsp}




| 
ApiName icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++OpenID List Broadcast Voice+++ | OpenIDListBroadcastVoice | {nbsp}




| 
toUser icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++List of Follower's openId+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Open id list broadcast image
`<wechat:open-id-list-broadcast-image>`



icon:cloud[] {nbsp} DataSense enabled

+++
OpenID List-Based Broadcast Image
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#OpenID_List-Based_Broadcast">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#OpenID_List-Based_Broadcast</a>
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of the message to be broadcast+++ |  | *x*{nbsp}




| 
ApiName icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++OpenID List Broadcast Image+++ | OpenIDListBroadcastImage | {nbsp}




| 
toUser icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++List of Follower's openId+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Open id list broadcast video
`<wechat:open-id-list-broadcast-video>`



icon:cloud[] {nbsp} DataSense enabled

+++
OpenID List-Based Broadcast Video
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#OpenID_List-Based_Broadcast">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#OpenID_List-Based_Broadcast</a>
+++


    
                            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++here is obtained on Basic Support->Transferring Multimedia Files+++ |  | *x*{nbsp}




| 
title  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The title of the message+++ |  | *x*{nbsp}




| 
description  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The description of the message+++ |  | *x*{nbsp}




| 
ApiName icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++OpenID List Broadcast Video+++ | OpenIDListBroadcastVideo | {nbsp}




| 
toUser icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++List of Follower's openId+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Preview broadcast article
`<wechat:preview-broadcast-article>`




+++
Send Preview Broadcast Article to OpenId
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Preview_API">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Preview_API</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
toUser  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++OpenID of the message receiver visible by the official account+++ |  | *x*{nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of the message to be broadcast+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Preview broadcast text
`<wechat:preview-broadcast-text>`




+++
Send Preview Broadcast Text to OpenId
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Preview_API">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Preview_API</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
toUser  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++OpenID of the message receiver visible by the official account+++ |  | *x*{nbsp}




| 
content  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Text content+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Preview broadcast voice
`<wechat:preview-broadcast-voice>`




+++
Send Preview Broadcast Voice to OpenId
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Preview_API">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Preview_API</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
toUser  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++OpenID of the message receiver visible by the official account+++ |  | *x*{nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of the message to be broadcast+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Preview broadcast image
`<wechat:preview-broadcast-image>`




+++
Send Preview Broadcast Image to OpenId
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Preview_API">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Preview_API</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
toUser  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++OpenID of the message receiver visible by the official account+++ |  | *x*{nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of the message to be broadcast+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Preview broadcast video
`<wechat:preview-broadcast-video>`




+++
Send Preview Broadcast Video to OpenId
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Preview_API">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Preview_API</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
toUser  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++OpenID of the message receiver visible by the official account+++ |  | *x*{nbsp}




| 
mediaId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++ID of the message to be broadcast+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Query broadcast status
`<wechat:query-broadcast-status>`




+++
Query Message Sending Status
</br><a href="http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Query_Message_Sending_Status">http://admin.wechat.com/wiki/index.php?title=Advanced_Broadcast_Interface#Query_Message_Sending_Status</a>
+++


    
        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
msgId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Message ID returned after a message is broadcast+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Get follower list
`<wechat:get-follower-list>`




+++
Get Follower List
</br><a href="http://admin.wechat.com/wiki/index.php?title=Follower_List">http://admin.wechat.com/wiki/index.php?title=Follower_List</a>
+++


    
        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
nextOpenId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The first OpenID to be loaded. Load from the first follower if it is empty+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Get user profile
`<wechat:get-user-profile>`




+++
Get User Profile
</br><a href="http://admin.wechat.com/wiki/index.php?title=User_Profile">http://admin.wechat.com/wiki/index.php?title=User_Profile</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
openId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Unique user ID for the official account+++ |  | *x*{nbsp}




| 
lang  | +++<a href="javadocs/org/mule/modules/wechat/WechatConnector/Lang.html">Lang</a>+++ | +++zh_CN: Simplified Chinese, zh_TW: Traditional Chinese, en: English+++ | en | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Create tag
`<wechat:create-tag>`




+++
Create Tag
</br><a href="http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Create_Tags">http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Create_Tags</a>
+++


    
        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
tagName  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Tag name (up to 30 characters)+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Query tags
`<wechat:query-tags>`




+++
Query Tags
</br><a href="http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Query_Tags">http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Query_Tags</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Editing tag
`<wechat:editing-tag>`




+++
Editing Tag
</br><a href="http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Editing_Tags">http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Editing_Tags</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
tagId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Tag ID+++ |  | *x*{nbsp}




| 
tagName  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Tag name (up to 30 characters)+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Deleting tag
`<wechat:deleting-tag>`




+++
Deleting Tag
</br><a href="http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Deleting_Tags">http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Deleting_Tags</a>
+++


    
        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
tagId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Tag ID+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Obtain followers with tag
`<wechat:obtain-followers-with-tag>`




+++
Obtaining the List of Followers Configured with a Tag
</br><a href="http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Obtaining_the_List_of_Followers_Configured_with_a_Tag">http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Obtaining_the_List_of_Followers_Configured_with_a_Tag</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
tagId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Tag ID+++ |  | *x*{nbsp}




| 
nextOpenId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Next Open ID+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Batch tag followers
`<wechat:batch-tag-followers>`



icon:cloud[] {nbsp} DataSense enabled

+++
Configuring Tags for Users in Batches
</br><a href="http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Configuring_Tags_for_Users_in_Batches">http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Configuring_Tags_for_Users_in_Batches</a>
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
tagId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Tag Id+++ |  | *x*{nbsp}




| 
ApiName icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Batch Tag Followers+++ | BatchTagFollowers | {nbsp}




| 
openidList icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++List of Follower's openId+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Batch untag followers
`<wechat:batch-untag-followers>`



icon:cloud[] {nbsp} DataSense enabled

+++
UnTags for Users in Batches
</br><a href="http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Canceling_Tags_for_Users_in_Batches">http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Canceling_Tags_for_Users_in_Batches</a>
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
tagId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Tag Id+++ |  | *x*{nbsp}




| 
ApiName icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Batch Untag Followers+++ | BatchUntagFollowers | {nbsp}




| 
openidList icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++List of Follower's openId+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Obtain follower tags
`<wechat:obtain-follower-tags>`




+++
Obtaining the List of Tags Configured for a User
</br><a href="http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Obtaining_the_List_of_Tags_Configured_for_a_User">http://admin.wechat.com/wiki/index.php?title=Tag_Management_API#Obtaining_the_List_of_Tags_Configured_for_a_User</a>
+++


    
        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
openId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Follower's openId+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Name remark
`<wechat:name-remark>`




+++
Set name remarks for specified users
</br><a href="http://admin.wechat.com/wiki/index.php?title=Name_Remarks">http://admin.wechat.com/wiki/index.php?title=Name_Remarks</a>
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
openId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Follower's openId+++ |  | *x*{nbsp}




| 
remark  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++New name remark, less than 30 characters.+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Obtain blacklist
`<wechat:obtain-blacklist>`




+++
Obtaining the Blacklist of an Official Account
</br><a href="http://admin.wechat.com/wiki/index.php?title=Blacklist_Management_API">http://admin.wechat.com/wiki/index.php?title=Blacklist_Management_API</a>
+++


    
        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
beginOpenId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The first OpenID to be loaded. Load from the first follower if it is empty+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Blacklist followers
`<wechat:blacklist-followers>`



icon:cloud[] {nbsp} DataSense enabled

+++
Blacklist Followers
</br><a href="http://admin.wechat.com/wiki/index.php?title=Blacklist_Management_API">http://admin.wechat.com/wiki/index.php?title=Blacklist_Management_API</a>
+++


    
                
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
ApiName icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Blacklist Followers+++ | BlacklistFollowers | {nbsp}




| 
openidList icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++List of Follower's openId+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================




---

=== Unblacklist followers
`<wechat:unblacklist-followers>`



icon:cloud[] {nbsp} DataSense enabled

+++
Unblacklist Followers
</br><a href="http://admin.wechat.com/wiki/index.php?title=Blacklist_Management_API">http://admin.wechat.com/wiki/index.php?title=Blacklist_Management_API</a>
+++


    
                
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
accessToken  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The certificate for the calling API. Mandatory if "Self Manage Access Token" config is true+++ |  | {nbsp}




| 
ApiName icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Unblacklist Followers+++ | UnblacklistFollowers | {nbsp}




| 
openidList icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++List of Follower's OpenId+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Hashmap+++
|======================







== Sources

---

=== Get access token
`<wechat:get-access-token>`




+++
Get Access Token
</br><a href="http://admin.wechat.com/wiki/index.php?title=Access_token">http://admin.wechat.com/wiki/index.php?title=Access_token</a>
+++


    

==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
| callback | +++SourceCallback+++ | +++Hashmap+++ |  | *x*{nbsp}
|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++void+++ | ++++++
|======================











